[package]
name = "olm-sys"
version = "0.1.0"
authors = ["BrainBlasted <brainblasted@disroot.org>"]
license = "GPL-3.0"
description = "Low level binding for libolm"
source = "https://gitlab.gnome.org/BrainBlasted/olm-sys"

[dependencies]

[build-dependencies]
bindgen = "0.26"
