[package]
name = "olm-sys"
version = "0.1.4"
authors = ["BrainBlasted <brainblasted@disroot.org>"]
license = "GPL-3.0-or-later"
description = "Low level binding for libolm"
repository = "https://gitlab.gnome.org/BrainBlasted/olm-sys"

[build-dependencies]
bindgen = "0.52.0"
